<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Country;
use App\Models\Coupon;
use App\Models\State;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class WorldSeeder extends Seeder
{

    public function run()
    {
        // $sql_file = public_path('ecommerce_World.sql');
        // $db = [
        //     'host' => '127.0.0.1',
        //     'database' => 'morasoftecommerce',
        //     'username' => 'root',
        //     'password' => null,
        // ];

        // exec("mysql --user={$db['username']} --password={$db['password']} --host={$db['host']} --database={$db['database']} < $sql_file");
        // Country::truncate();

        $countries = [
            ['name' => 'Egypt', 'status' => 0],
            ['name' => 'Afghanistan', 'status' => 0],
            ['name' => 'Åland Islands', 'status' => 0],
            ['name' => 'Albania', 'status' => 0],
            ['name' => 'Algeria', 'status' => 0],
            ['name' => 'American Samoa', 'status' => 0],
            ['name' => 'Andorra', 'status' => 0],
            ['name' => 'Angola', 'status' => 0],
            ['name' => 'Anguilla', 'status' => 0],
            ['name' => 'Antarctica', 'status' => 0],
            ['name' => 'Antigua and Barbuda', 'status' => 0],
            ['name' => 'Argentina', 'status' => 0],
            ['name' => 'Armenia', 'status' => 0],
            ['name' => 'Aruba', 'status' => 0],
            ['name' => 'Australia', 'status' => 0],
            ['name' => 'Austria', 'status' => 0],
            ['name' => 'Azerbaijan', 'status' => 0],
            ['name' => 'Bahamas', 'status' => 0],
            ['name' => 'Bahrain', 'status' => 0],
            ['name' => 'Bangladesh', 'status' => 0],
            ['name' => 'Barbados', 'status' => 0],
            ['name' => 'Belarus', 'status' => 0],
            ['name' => 'Belgium', 'status' => 0],
            ['name' => 'Belize', 'status' => 0],
            ['name' => 'Benin', 'status' => 0],
            ['name' => 'Bermuda', 'status' => 0],
            ['name' => 'Bhutan', 'status' => 0],
            ['name' => 'Bolivia', 'status' => 0],
            ['name' => 'Bosnia and Herzegovina', 'status' => 0],
            ['name' => 'Botswana', 'status' => 0],
            ['name' => 'Bouvet Island', 'status' => 0],
            ['name' => 'Brazil', 'status' => 0],
            ['name' => 'British Indian Ocean Territory', 'status' => 0],
            ['name' => 'Brunei Darussalam', 'status' => 0],
            ['name' => 'Bulgaria', 'status' => 0],
            ['name' => 'Burkina Faso', 'status' => 0],
            ['name' => 'Burundi', 'status' => 0],
            ['name' => 'Cambodia', 'status' => 0],
            ['name' => 'Cameroon', 'status' => 0],
            ['name' => 'Canada', 'status' => 0],
            ['name' => 'Cape Verde', 'status' => 0],
            ['name' => 'Cayman Islands', 'status' => 0],
            ['name' => 'Central African Republic', 'status' => 0],
            ['name' => 'Chad', 'status' => 0],
            ['name' => 'Chile', 'status' => 0],
            ['name' => 'China', 'status' => 0],
            ['name' => 'Christmas Island', 'status' => 0],
            ['name' => 'Cocos (Keeling) Islands', 'status' => 0],
            ['name' => 'Colombia', 'status' => 0],
            ['name' => 'Comoros', 'status' => 0],
            ['name' => 'Congo', 'status' => 0],
            ['name' => 'Congo, The Democratic Republic of the', 'status' => 0],
            ['name' => 'Cook Islands', 'status' => 0],
            ['name' => 'Costa Rica', 'status' => 0],
            ['name' => 'Cote D\'Ivoire', 'status' => 0],
            ['name' => 'Croatia', 'status' => 0],
            ['name' => 'Cuba', 'status' => 0],
            ['name' => 'Cyprus', 'status' => 0],
            ['name' => 'Czech Republic', 'status' => 0],
            ['name' => 'Denmark', 'status' => 0],
            ['name' => 'Djibouti', 'status' => 0],
            ['name' => 'Dominica', 'status' => 0],
            ['name' => 'Dominican Republic', 'status' => 0],
            ['name' => 'Ecuador', 'status' => 0],
            ['name' => 'El Salvador', 'status' => 0],
            ['name' => 'Equatorial Guinea', 'status' => 0],
            ['name' => 'Eritrea', 'status' => 0],
            ['name' => 'Estonia', 'status' => 0],
            ['name' => 'Ethiopia', 'status' => 0],
            ['name' => 'Falkland Islands (Malvinas)', 'status' => 0],
            ['name' => 'Faroe Islands', 'status' => 0],
            ['name' => 'Fiji', 'status' => 0],
            ['name' => 'Finland', 'status' => 0],
            ['name' => 'France', 'status' => 0],
            ['name' => 'French Guiana', 'status' => 0],
            ['name' => 'French Polynesia', 'status' => 0],
            ['name' => 'French Southern Territories', 'status' => 0],
            ['name' => 'Gabon', 'status' => 0],
            ['name' => 'Gambia', 'status' => 0],
            ['name' => 'Georgia', 'status' => 0],
            ['name' => 'Germany', 'status' => 0],
            ['name' => 'Ghana', 'status' => 0],
            ['name' => 'Gibraltar', 'status' => 0],
            ['name' => 'Greece', 'status' => 0],
            ['name' => 'Greenland', 'status' => 0],
            ['name' => 'Grenada', 'status' => 0],
            ['name' => 'Guadeloupe', 'status' => 0],
            ['name' => 'Guam', 'status' => 0],
            ['name' => 'Guatemala', 'status' => 0],
            ['name' => 'Guernsey', 'status' => 0],
            ['name' => 'Guinea', 'status' => 0],
            ['name' => 'Guinea-Bissau', 'status' => 0],
            ['name' => 'Guyana', 'status' => 0],
            ['name' => 'Haiti', 'status' => 0],
            ['name' => 'Heard Island and Mcdonald Islands', 'status' => 0],
            ['name' => 'Holy See (Vatican City State)', 'status' => 0],
            ['name' => 'Honduras', 'status' => 0],
            ['name' => 'Hong Kong', 'status' => 0],
            ['name' => 'Hungary', 'status' => 0],
            ['name' => 'Iceland', 'status' => 0],
            ['name' => 'India', 'status' => 0],
            ['name' => 'Indonesia', 'status' => 0],
            ['name' => 'Iran, Islamic Republic Of', 'status' => 0],
            ['name' => 'Iraq', 'status' => 0],
            ['name' => 'Ireland', 'status' => 0],
            ['name'=> 'Israel', 'status'=> 0],
            ['name'=> 'Italy', 'status'=> 0],
            ['name'=> 'Jamaica', 'status'=> 0],
            ['name'=> 'Japan', 'status'=> 0],
            ['name'=> 'Jersey', 'status'=> 0],
            ['name'=> 'Jordan', 'status'=> 0],
            ['name'=> 'Kazakhstan', 'status'=> 0],
            ['name'=> 'Kenya', 'status'=> 0],
            ['name'=> 'Kiribati', 'status'=> 0],
            ['name'=> 'Korea North', 'status'=> 0],
            ['name'=> 'Korea South', 'status'=> 0],
            ['name'=> 'Kuwait', 'status'=> 0],
            ['name'=> 'Kyrgyzstan', 'status'=> 0],
            ['name'=> 'Laos', 'status'=> 0],
            ['name'=> 'Latvia', 'status'=> 0],
            ['name'=> 'Lebanon', 'status'=> 0],
            ['name'=> 'Lesotho', 'status'=> 0],
            ['name'=> 'Liberia', 'status'=> 0],
            ['name'=> 'Libya', 'status'=> 0],
            ['name'=> 'Liechtenstein', 'status'=> 0],
            ['name'=> 'Lithuania', 'status'=> 0],
            ['name'=> 'Luxembourg', 'status'=> 0],
            ['name'=> 'Macau S.A.R.', 'status'=> 0],
            ['name'=> 'Macedonia', 'status'=> 0],
            ['name'=> 'Madagascar', 'status'=> 0],
            ['name'=> 'Malawi', 'status'=> 0],
            ['name'=> 'Malaysia', 'status'=> 0],
            ['name'=> 'Maldives', 'status'=> 0],
            ['name'=> 'Mali', 'status'=> 0],
            ['name'=> 'Malta', 'status'=> 0],
            ['name'=> 'Man (Isle of)', 'status'=> 0],
            ['name'=> 'Marshall Islands', 'status'=> 0],
            ['name'=> 'Martinique', 'status'=> 0],
            ['name'=> 'Mauritania', 'status'=> 0],
            ['name'=> 'Mauritius', 'status'=> 0],
            ['name'=> 'Mayotte', 'status'=> 0],
            ['name'=> 'Mexico', 'status'=> 0],
            ['name'=> 'Micronesia', 'status'=> 0],
            ['name'=> 'Moldova', 'status'=> 0],
            ['name'=> 'Monaco', 'status'=> 0],
            ['name'=> 'Mongolia', 'status'=> 0],
            ['name'=> 'Montenegro', 'status'=> 0],
            ['name'=> 'Montserrat', 'status'=> 0],
            ['name'=> 'Morocco', 'status'=> 0],
            ['name'=> 'Mozambique', 'status'=> 0],
            ['name'=> 'Myanmar', 'status'=> 0],
            ['name'=> 'Namibia', 'status'=> 0],
            ['name'=> 'Nauru', 'status'=> 0],
            ['name'=> 'Nepal', 'status'=> 0],
            ['name'=> 'Bonaire, Sint Eustatius and Saba', 'status'=> 0],
            ['name'=> 'Netherlands The', 'status'=> 0],
            ['name'=> 'New Caledonia', 'status'=> 0],
            ['name'=> 'New Zealand', 'status'=> 0],
            ['name'=> 'Nicaragua', 'status'=> 0],
            ['name'=> 'Niger', 'status'=> 0],
            ['name'=> 'Nigeria', 'status'=> 0],
            ['name'=> 'Niue', 'status'=> 0],
            ['name'=> 'Norfolk Island', 'status'=> 0],
            ['name'=> 'Northern Mariana Islands', 'status'=> 0],
            ['name'=> 'Norway', 'status'=> 0],
            ['name'=> 'Oman', 'status'=> 0],
            ['name'=> 'Pakistan', 'status'=> 0],
            ['name'=> 'Palau', 'status'=> 0],
            ['name'=> 'Palestinian Territory Occupied', 'status'=> 0],
            ['name'=> 'Panama', 'status'=> 0],
            ['name'=> 'Papua new Guinea', 'status'=> 0],
            ['name'=> 'Paraguay', 'status'=> 0],
            ['name'=> 'Peru', 'status'=> 0],
            ['name'=> 'Philippines', 'status'=> 0],
            ['name'=> 'Pitcairn Island', 'status'=> 0],
            ['name'=> 'Poland', 'status'=> 0],
            ['name'=> 'Portugal', 'status'=> 0],
            ['name'=> 'Puerto Rico', 'status'=> 0],
            ['name'=> 'Qatar', 'status'=> 0],
            ['name'=> 'Reunion', 'status'=> 0],
            ['name'=> 'Romania', 'status'=> 0],
            ['name'=> 'Russia', 'status'=> 0],
            ['name'=> 'Rwanda', 'status'=> 0],
            ['name'=> 'Saint Helena', 'status'=> 0],
            ['name'=> 'Saint Kitts And Nevis', 'status'=> 0],
            ['name'=> 'Saint Lucia', 'status'=> 0],
            ['name'=> 'Saint Pierre and Miquelon', 'status'=> 0],
            ['name'=> 'Saint Vincent And The Grenadines', 'status'=> 0],
            ['name'=> 'Saint-Barthelemy', 'status'=> 0],
            ['name'=> 'Saint-Martin (French part)', 'status'=> 0],
            ['name'=> 'Samoa', 'status'=> 0],
            ['name'=> 'San Marino', 'status'=> 0],
            ['name'=> 'Sao Tome and Principe', 'status'=> 0],
            ['name'=> 'Saudi Arabia', 'status'=> 0],
            ['name'=> 'Senegal', 'status'=> 0],
            ['name'=> 'Serbia', 'status'=> 0],
            ['name'=> 'Seychelles', 'status'=> 0],
            ['name'=> 'Sierra Leone', 'status'=> 0],
            ['name'=> 'Singapore', 'status'=> 0],
            ['name'=> 'Slovakia', 'status'=> 0],
            ['name'=> 'Slovenia', 'status'=> 0],
            ['name'=> 'Solomon Islands', 'status'=> 0],
            ['name'=> 'Somalia', 'status'=> 0],
            ['name'=> 'South Africa', 'status'=> 0],
            ['name'=> 'South Georgia', 'status'=> 0],
            ['name'=> 'South Sudan', 'status'=> 0],
            ['name'=> 'Spain', 'status'=> 0],
            ['name'=> 'Sri Lanka', 'status'=> 0],
            ['name'=> 'Sudan', 'status'=> 0],
            ['name'=> 'Suriname', 'status'=> 0],
            ['name'=> 'Svalbard And Jan Mayen Islands', 'status'=> 0],
            ['name'=> 'Swaziland', 'status'=> 0],
            ['name'=> 'Sweden', 'status'=> 0],
            ['name'=> 'Switzerland', 'status'=> 0],
            ['name'=> 'Syria', 'status'=> 0],
            ['name'=> 'Taiwan', 'status'=> 0],
            ['name'=> 'Tajikistan', 'status'=> 0],
            ['name'=> 'Tanzania', 'status'=> 0],
            ['name'=> 'Thailand', 'status'=> 0],
            ['name'=> 'Togo', 'status'=> 0],
            ['name'=> 'Tokelau', 'status'=> 0],
            ['name'=> 'Tonga', 'status'=> 0],
            ['name'=> 'Trinidad And Tobago', 'status'=> 0],
            ['name'=> 'Tunisia', 'status'=> 0],
            ['name'=> 'Turkey', 'status'=> 0],
            ['name'=> 'Turkmenistan', 'status'=> 0],
            ['name'=> 'Turks And Caicos Islands', 'status'=> 0],
            ['name'=> 'Tuvalu', 'status'=> 0],
            ['name'=> 'Uganda', 'status'=> 0],
            ['name'=> 'Ukraine', 'status'=> 0],
            ['name'=> 'United Arab Emirates', 'status'=> 0],
            ['name'=> 'United Kingdom', 'status'=> 0],
            ['name'=> 'United Status', 'status'=> 0],
            ['name'=> 'United Status Minor Outlying Islands', 'status'=> 0],
            ['name'=> 'Uruguay', 'status'=> 0],
            ['name'=> 'Uzbekistan', 'status'=> 0],
            ['name'=> 'Vanuatu', 'status'=> 0],
            ['name'=> 'Vatican City State (Holy See)', 'status'=> 0],
            ['name'=> 'Venezuela', 'status'=> 0],
            ['name'=> 'Vietnam', 'status'=> 0],
            ['name'=> 'Virgin Islands (British)', 'status'=> 0],
            ['name'=> 'Virgin Islands (US)', 'status'=> 0],
            ['name'=> 'Wallis And Futuna Islands', 'status'=> 0],
            ['name'=> 'Western Sahara', 'status'=> 0],
            ['name'=> 'Yemen', 'status'=> 0],
            ['name'=> 'Zambia', 'status'=> 0],
            ['name'=> 'Zimbabwe', 'status'=> 0],
            ['name'=> 'Kosovo', 'status'=> 0],
            ['name'=> 'Curaçao', 'status'=> 0],
            ['name'=> 'Sint Maarten (Dutch part)', 'status'=> 0],
        ];
        foreach ($countries as $key => $value) {
            Country::create($value);
        }


        //states
        $states=[
            ['name' => 'Cairo', 'country_id'=>1 ,'status' => 0],
            ['name' => 'Alexandria', 'country_id'=>1 ,'status' => 0],
            ['name' => 'Giza', 'country_id'=>1 ,'status' => 0],
            ['name' => 'Luxor', 'country_id'=>1 ,'status' => 0],
            ['name' => 'Asyut', 'country_id'=>1 ,'status' => 0],
            ['name' => 'Beheira', 'country_id'=>1 ,'status' => 0],
            ['name' => 'Beni Suef', 'country_id'=>1 ,'status' => 0],
        ];
        foreach ($states as $key => $value) {
            State::create($value);
        }


        //cities
        $cities=[
            ['name' => 'ramsis', 'state_id'=>1,'status' => 0],
            ['name' => 'dar elsalam', 'state_id'=>1,'status' => 0],
            ['name' => 'helwan', 'state_id'=>1,'status' => 0],
            ['name' => 'el raml', 'state_id'=>2,'status' => 0],
            ['name' => 'giza', 'state_id'=>3,'status' => 0],
            ['name' => 'dokki', 'state_id'=>1,'status' => 0],
        ];
            foreach ($cities as $key => $value) {
                City::create($value);
            }
    }
}
